apiVersion: extensions/v1beta1
kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 80
    name: http
  type: ClusterIP
